# =========================
# PERSISTENCE (RDB)
# =========================
save 60 10000
save 300 100
save 900 1

# =========================
# AOF (APPEND ONLY FILE)
# =========================
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# =========================
# PERFORMANCE
# =========================
maxmemory-policy allkeys-lru

# =========================
# DATA DIRECTORY
# =========================
dir /data